### ISSUE TITLE
Record a Screenflow?

### ISSUE THREAD

**Issue by alexgann** [IntuitiveWebSolutions/VimConf#33]
A video (with keystrokes displayed) is worth 1,000 README.md's? 

Seriously though - I think watching the maintainer(s) code using this conf would be the fastest way to launch others into using it effectively.

**Comment by alexgann** [comment]
@beardedprojamz - this still may be true, perhaps especially so with the slew of new Client Devs coming on. :stuck_out_tongue:

**Comment by beardedprojamz** [comment]
I don't actually use this vim configuration anymore - I've went off the beaten path long ago. I've got my own custom thing going on [over here](https://github.com/beardedprojamz/DotFiles/blob/master/files/.vimrc). I've also been using [NeoVim](https://github.com/neovim/neovim) lately

**Comment by alexgann** [comment]
Awesome - I'll take a look.  I forget if it was Chris or Scott, but someone said they had thought they were fast in vim until they met you.  Screenflow would still be rad, even with your new conf :)
